### ISSUE TITLE
Android部署推理demo

### ISSUE THREAD

**Issue by DemingCheng** [alibaba-damo-academy/kws-training-suite#7]
您好，请问后续会提供Android端的部署推理demo么？谢谢

**Comment by bincard** [comment]
你好，这个项目训练的模型主要针对麦克风阵列，不适合移动端使用。我们在魔搭社区也有提供移动端的唤醒方案，可以看看这个列表 https://modelscope.cn/models?page=1&tasks=keyword-spotting&type=audio
