### ISSUE TITLE
pipiline.py中num_syn的设置问题

### ISSUE THREAD

**Issue by lingyuwangwang** [alibaba-damo-academy/kws-training-suite#8]
请问如果训练套件中的keywords设置如下：
kws_decode_desc:
- ni_hao_tian_mao,1,2,3,4
- jin_tian_de_tian_qi,5,3,6,3,7
那么pipeline.py中，这个代码该怎么设置
如果默认训练一个4字唤醒词时，模型输出维度为5，即模型4个字 + 其他
    if num_syn != 5:
        kwargs['num_syn'] = num_syn
目前我有2个唤醒词，一个四字一个五字，有7个分类。请问按照上面的例子，模型的输出维度是8吗？

**Comment by bincard** [comment]
您的分析正确，应该是8
